label ch4_main:
    stop music fadeout 2.0
    scene bg residential_day
    with dissolve_scene_full

    play music t6

    "Ya es Domingo."
    if ch4_scene == "natsuki":
        "He estado cada vez más ansioso por la próxima visita de Natsuki."
        "Sigo diciéndome que no hay razón para estar nervioso, pero eso no ayuda mucho."
        "Me pregunto si ella actuará de manera diferente cuando seamos sólo nosotros dos."
        "Entre tanto, me ha estado enviando muchos mensajes de texto."
        "Nos enviamos uno después de intercambiar números para verificar, pero se convirtieron en una conversación."
        "Ella tiene una personalidad diferente en los mensajes, usando toneladas de emojis y mucho lenguaje lindo."
        "También le gusta mucho quejarse de las cosas, aunque ya sabía que eso iba a pasar."
        "Pero dejando de lado a Natsuki..."
    else:
        "He estado cada vez más ansioso por la próxima visita de Yuri."
        "Sigo diciéndome que no hay razón para estar nervioso, pero no ayuda mucho."
        "Yuri es claramente una persona introvertida y también una persona íntima en general."
        "No hay duda de que se abrirá un poco cuando seamos sólo nosotros dos."
        "Entre tanto, hemos estado enviándonos mensajes de texto de vez en cuando."
        "Al principio era muy aprensiva, pero no pasó mucho tiempo antes de que me contara más sobre ella."
        "Pero dejando de lado a Yuri..."
    "No he escuchado nada de Sayori desde que se fue temprano del club el otro día."
    "No es como si nos enviáramos mensajes todo el tiempo..."
    "Pero he estado preocupado por ella en el fondo de mi mente."
    "Entre lo que Sayori dijo y lo que dijo Monika..."
    "¿Está realmente bien para mí dejar de lado los sentimientos de Sayori cuando ella me necesita?"

    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "Decido visitar a Sayori antes de que [ch4_name] venga a mi casa."
    "En lugar de preguntar, simplemente le digo que voy a visitarla, al igual que lo hemos hecho en el pasado."
    "Una vez que llego a la casa de Sayori, llamo a la puerta antes de entrar por mi cuenta."
    "Solíamos jugar tan a menudo que nos hemos acostumbrado a simplemente entrar en nuestras casas como si fuéramos de la familia."
    scene black with wipeleft
    "La casa está silenciosa."
    "Sayori no está en el primer piso, así que asumo que está en su habitación."
    "Es extraño que no baje corriendo a saludarme."
    "Me dirijo a su habitación, donde finalmente la encuentro."
    scene bg sayori_bedroom with wipeleft
    mc "¿Sayori?"
    play music t10
    show sayori 1ba zorder 2 at t11
    s "Hola, [player]~"
    show sayori 1by
    "Me siento en el piso."
    "Sayori fuerza una sonrisa, pero es fácil decir que ella está diferente."
    "Hay un minuto de silencio entre nosotros."
    s "No has venido aquí en mucho tiempo, ¿verdad?"
    mc "Ah...supongo que tienes razón."
    mc "Ha pasado mucho tiempo."
    mc "Realmente nada ha cambiado, ¿verdad?"
    "La habitación de Sayori está tan desordenada como siempre."
    "También reconozco los mismos animales de peluche y decoraciones que ha tenido durante años."
    s 2bl "Jejeje~"
    s "Si vinieras con más frecuencia, no sería un desastre."
    mc "Eso es porque terminaría limpiándolo por ti..."
    s 1bb "¿Por qué de la nada quisiste venir?"
    s "¿No se supone que verás a [ch4_name] hoy?"
    mc "Sí, pero..."
    mc "...Espera, ¿cómo lo sabes?"
    "Sayori ya se había ido cuando lo decidimos en la última reunión."
    s 1ba "Monika me lo dijo."
    s "Es natural que ella me mantenga informada sobre los preparativos del festival, ¿no es así?"
    mc "Ah, eso es verdad..."
    mc "¿Y tú?"
    mc "¿No vas a ayudar a Monika hoy?"
    s 4bb "¡Por supuesto!"
    s "Pero sólo la estoy ayudando en línea."
    s "No planeábamos reunirnos ni nada parecido."
    mc "Ah, entonces sólo somos [ch4_name] y yo..."
    s 1ba "Sip~"
    "Hay más silencio entre nosotros."
    show sayori 1bk
    "Sayori mira en una dirección aleatoria."
    "Todo sobre su comportamiento es realmente poco característico."
    "Finalmente toco el punto."
    mc "Sólo...quería ver cómo estabas."
    mc "Después de que te fuiste el viernes."
    mc "¡Cuando algo anda mal, no puedes esconderlo de mí!"
    mc "Te conozco demasiado bien."
    mc "Entonces..."
    "Sayori sonríe, sacudiendo la cabeza."
    s 1bd "Eso no está bien, [player]."
    mc "¿Eh?"
    s "¿Por qué no puede ser como siempre ha sido?"
    s 1by "Esto es todo culpa mía."
    s "Si no me hubiera vuelto tan débil y accidentalmente haber expresado mis sentimientos..."
    s 1bk "Si no hubiera cometido ese error estúpido..."
    s "Entonces no habrías estado preocupado por mí en absoluto."
    s "No habrías venido aquí."
    s 1bd "Ni siquiera habrías estado pensando en mí en este momento."
    s "Pero esto...ss sólo mi castigo, ¿no es así?"
    s "Me castigan por ser tan egoísta."
    s "Creo que es por eso que el mundo decidió que vinieras hoy."
    s "Simplemente quiere torturarme."
    s 4bq "Jejeje~"
    mc "¡Sayori!"
    show sayori 4bb
    "Agarro a Sayori por los hombros."
    mc "¡¿Qué diablos estás diciendo?!"
    mc "¿Te estás escuchando en este momento?"
    mc "Sé que te sucedió algo."
    mc "No hay otra explicación para que seas así."
    mc "¡Entonces dime, ya...!"
    mc "¡Hasta que lo sepa, no podré dejar de pensar en eso!"
    s 4bl "Ah..."
    s "Jajaja..."
    "Sayori me muestra una sonrisa vacía."
    s 4by "Realmente me pones en una trampa, [player]."
    s "Pero..."
    s 1ba "Estás equivocado."
    s "No me pasó nada."
    s "Siempre he sido así."
    s "Sólo lo estás viendo por primera vez."
    mc "¿Ver qué?"
    mc "¿De qué estás hablando, Sayori?"
    s 1bq "Jejeje~"
    s 1ba "Realmente vas a hacer que lo diga, ¿verdad, [player]?"
    s "Supongo que no tengo otra opción esta vez."
    s 1bc "El asunto es..."
    s "He tenido una depresión realmente severa durante toda mi vida."
    s 1bb "¿Sabías eso?"
    s "¿Por qué crees que llego tarde a la escuela todos los días?"
    s "Porque casi todos los días, ni siquiera puedo encontrar una razón para salir de la cama."
    s 1by "¿Qué razón hay para hacer algo cuando sé completamente lo inútil que soy?"
    s "¿Por qué ir a la escuela?"
    s "¿Por qué comer?"
    s "¿Por qué hacer amigos?"
    s "¿Por qué hacer que otras personas desperdicien su energía y su preocupación al gastarlas en mí?"
    s "Eso es lo que se siente."
    s "Y es por eso que sólo quiero hacer felices a todos..."
    s "Sin que nadie se preocupe por mí."
    mc "..."
    "Estoy en shock."
    "Ni siquiera puedo descubrir cómo responder."
    "¿Cómo es posible que Sayori me lo haya ocultado durante todo este tiempo?"
    "¿Realmente deseaba tanto que yo no pensara en ella?"
    mc "...¿Por qué, Sayori?"
    s 1bg "¿Eh...?"
    mc "¿Por qué nunca me has contado sobre esto?"
    mc "Casi parece que he sido traicionado como tu mejor amigo."
    mc "¡Porque si lo supiera, hubiera hecho todo lo posible para apoyarte!"
    mc "Incluso si no hay mucho que podría hacer..."
    mc "Hubiera intentado hacer cada día un poco mejor para ti."
    mc "¡Por eso soy tu amigo!"
    mc "¡Todo lo que tenías que hacer era decirme!"
    s 1bk "No entiendes para nada, [player]."
    s "¿Por qué crees que no te lo dije?"
    s 1bd "Porque si te lo dijera, entonces tendrías que perder esfuerzo cuidando de mí en lugar de hacer cosas importantes."
    s "No quiero que te importe."
    s "Es agridulce, cuando la gente trata de preocuparse por mí."
    s 1ba "A veces se siente bien."
    s "Pero también se siente como ser golpeado con un bate en la cabeza."
    s 4bq "Jajaja~"
    s 4ba "Es por eso que deseaba tanto que hicieras amistades con las demás..."
    s "Ayudar a todos a ser felices juntos es lo mejor para mí."
    s 1bb "Pero luego, también descubrí algo más."
    s "Ver que haces amigas tan cercanas en el club..."
    s 1bk "Se siente como una lanza atravesando mi corazón."
    s "Entonces, es por eso."
    s "Es por eso que decidí que el mundo sólo quiere torturarme."
    s 1by "Cada camino me lleva a nada más que dolor."
    s "Jajaja~"
    mc "Tienes razón de que no entiendo..."
    mc "No entiendo tus sentimientos para nada, Sayori."
    mc "Pero no necesito entender."
    mc "Lo que sea necesario para ayudarte a dejar de sufrir..."
    mc "Eso es lo que haré."
    s 1bd "No, [player]."
    s "No hay nada."
    s "Nada en absoluto."
    s "Lo único que podría haber ayudado era dejar las cosas como estaban."
    s 1bk "Pero fui egoísta."
    s "Finalmente te demostré la persona horrible que soy."
    "Las lágrimas bañan la cara de Sayori."
    s 1bv "Te hice unirte al club de literatura porque fui egoísta."
    s "Y fui castigada por el dolor de mi corazón de una manera que no pude entender."
    s "Y ahora viniste aquí y también te hice daño."
    s 1bt "Sólo soy débil y egoísta."
    s "Eso es todo lo que soy."
    s "Y es por eso que voy a aceptar estos castigos."
    s 1bv "¡Porque merezco hasta el último de...!"
    "Sin pensarlo, una vez más tomo los hombros de Sayori."
    "Esta vez, la estrecho en un fuerte abrazo."
    scene black with dissolve_cg
    s "A-Ah--"
    s "[player]..."
    mc "Sayori."
    mc "No me importa si te sientes egoísta."
    mc "Estoy muy feliz de que me hayas convencido de unirme al club."
    mc "Verte todos los días hace que valga la pena lo suficiente."
    mc "Si me hago amigo de todas, entonces eso es sólo un extra."
    mc "Pero por favor nunca subestimes lo mucho que me preocupo por ti."
    mc "No lo haría de ninguna otra manera."
    s "[player]..."
    "Sayori no me está abrazando."
    "A diferencia de mis brazos envueltos alrededor de ella, los brazos de Sayori permanecen a su lado."
    "Ella comienza a sollozar al lado de mi oreja."
    s "No..."
    s "No me hagas...esto..."
    s "Por favor, no me hagas esto..."
    s "[player]..."
    s "Yo..."
    "Sayori apenas logra hablar entre sus sollozos."
    "No sé si estoy haciendo lo correcto."
    "Pero todo lo que quiero es que ella sepa que me importa."
    mc "Si te auto denominas egoísta, entonces debes permitir que yo también sea egoísta."
    mc "No importa lo que sea necesario, descubriré qué debe cambiar."
    mc "Haré que estos sentimientos desaparezcan."
    mc "Y si hay algo que necesites que haga..."
    mc "Entonces será mejor que me digas."
    mc "Me enojaré si no lo haces."
    s "..."
    s "Yo...no lo sé..."
    s "No lo sé..."
    s "No lo sé."
    "Suavemente, Sayori finalmente me rodea con sus brazos."
    s "No sé nada."
    s "Todo es realmente aterrador..."
    s "No entiendo ninguno de mis sentimientos, [player]..."
    s "La única vez que no siento nada es cuando siento dolor."
    s "Pero..."
    s "Tus abrazos son tan cálidos..."
    s "...Y eso también es realmente aterrador."
    scene bg sayori_bedroom
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Sayori me suelta."
    "Mientras lo hace, la suelto también."
    mc "El festival es mañana."
    s 1bk "Sí..."
    mc "Va a ser divertido, ¿verdad?"
    s "Sí."
    mc "¿Te gustaría que pase todo el día contigo?"
    s 1bh "U-Um..."
    s "Ah--"
    mc "Es lo que quiero."
    mc "Lo prometo"
    s 1bk "Yo..."
    s "Creo que eso estaría bien..."
    mc "Sí."
    "Sayori se seca los ojos."
    "Si pudiera pasar todo el día aquí, lo haría."
    mc "De todos los días, este tiene que ser aquel en el que tengo otros planes..."
    mc "Tal vez debería cancelar--"
    s 1bh "¡No, no...!"
    s 1bg "Por favor, no..."
    s "Si hicieras eso...entonces realmente no te lo perdonaría."
    mc "Pero..."
    mc "Es casi la hora de que [ch4_name] vaya a mi casa..."
    mc "Por lo menos, ¿quieres venir y ayudarnos?"
    mc "Sería divertido."
    "Para mi sorpresa, Sayori niega con la cabeza."
    s 1bd "Lo siento."
    s "No sé si eso sería muy bueno para mí en estos momentos."
    s "¿Lo entiendes, verdad?"
    mc "Ah..."
    mc "Es...algo difícil de entender para mí."
    mc "Pero estoy haciendo todo lo posible."
    s "Está bien."
    s "No te preocupes demasiado por eso."
    s 4ba "Te veré mañana, ¿de acuerdo?"
    mc "...Está bien."
    mc "Esperaré con ansias."
    scene bg residential_day with wipeleft_scene
    "Me despido de Sayori y salgo de su casa."
    "De regreso a casa, todavía me siento incómodo."
    "Pero es difícil para mí seguir pensando cuando [ch4_name] está a punto de llegar..."
    "Creo que Sayori tiene razón."
    "No debería preocuparme demasiado, y definitivamente vamos a pasar un gran momento mañana."
    "¡Debería centrarme en lo que me espera!"
    call expression "ch4_exclusive_" + ch4_scene from _call_expression_20
    call ch4_end from _call_ch4_end

    return


label ch4_exclusive_natsuki:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "Sólo paso unos minutos en casa esperando ansiosamente la llegada de Natsuki."
    "Antes de darme cuenta, me envía un mensaje de texto para avisarme que está afuera de la puerta."
    "Sin demora, abro la puerta para dejarla entrar."
    show natsuki 2bj zorder 2 at t11
    mc "..."
    n "¿Qué onda?"
    mc "...Hey."
    "No sé lo que esperaba, pero ver a Natsuki con algo más que su uniforme escolar me asombró por completo."
    "Verla con tan linda ropa hace que el uniforme parezca totalmente inadecuado en comparación."
    n 4bc "¡Caray, no lo hagas incomodo desde el inicio!"
    n "Va a ser una tarde larga, así que no te comportes raro sólo porque no estás acostumbrado a verme fuera de la escuela."
    n "Como sea, voy a pasar."
    scene bg kitchen
    show natsuki 1bj zorder 2 at t11
    with wipeleft
    mc "Veo que trajiste muchas cosas..."
    "Natsuki lleva una bolsa grande que probablemente esté llena de utensilios para hornear."
    n 2bj "Bueno, no quería tener que venir hasta acá sólo para descubrir que tu cocina no está equipada para el trabajo."
    n "Compraste todo lo que te pedí, ¿verdad?"
    mc "Sí, lo hice."
    "Ayer, Natsuki me pidió comprar un montón de ingredientes por si no los tenía en casa."
    n 2bl "¡Bien!"
    n "Me alegro de poder contar contigo para que hagas tu parte."
    mc "Bueno...por supuesto."
    "Estoy sorprendido de escuchar a Natsuki decir eso de repente, en lugar de algo sarcástico como suele hacer."
    "¿Podría ser que después de todo es un poco diferente fuera de la escuela?"
    mc "De todos modos, vamos a la cocina..."
    n 2by "¿Qué?, ¿ni siquiera vas a ofrecerte para quitarme esta pesada bolsa?"
    n "¿Dónde está tu hospitalidad, [player]?"
    mc "Vamos..."
    mc "¿Desde cuándo necesito ser un caballero contigo?"
    "Agarro la bolsa que Natsuki me entrega."
    mc "Ghk--"
    mc "¡Está ridículamente pesada--!"
    n 4bz "¡Jajaja!"
    n "La cargué todo el camino hasta aquí."
    n 4bl "¿Estás impresionado?"
    mc "Ya veo..."
    mc "Sí, estoy impresionado, Natsuki."
    mc "Parece que siempre te subestimo."
    n 4by "Jejeje~"
    n "Es porque soy tan pequeña, ¿no?"
    n 4ba "Idiota."
    "Natsuki golpea su puño en mi pecho."
    mc "Oye, oye."
    mc "Tu tamaño no tiene nada que ver con eso."
    mc "¿Realmente odias ser tan pequeña?"
    n 1bk "¿Eh?"
    n "Um..."
    n 1bc "No es que lo odie..."
    n "Quiero decir, a veces me gusta probar que la gente está equivocada cuando piensan que sólo valgo mi talla."
    n 1ba "Es divertido que sea más pequeña y, a la vez, mejor que otras personas."
    n "Pero..."
    n 5bw "...¡Caray, no importa!"
    n "¿Qué me estás haciendo decir?"
    n 5bq "¡No creas que puedes hacerme hablar de cosas raras sólo porque no estamos en la escuela!"
    n "¿Vamos a comenzar, o qué? Hay muchas cosas que debo enseñarte."
    mc "Jajaja."
    n 5bn "¿Qué?"
    mc "Eso es un poquito más como tú."
    mc "Eres más divertida cuando hablas así."
    n 1bm "¡O-Oye!"
    n "¡Ahora {i}estás{/i} tratándome como una niña!"
    n "Sólo estaba tratando de ser un poco más amable contigo, ¿sabes?."
    n 1br "Y sólo porque no tengo una figura madura y sexy como Yuri no significa que debas tratarme como--"
    n 1bo "A-Ah--"
    "Natsuki se da cuenta de sus palabras, y su rostro se pone rojo."
    mc "Natsuki..."
    n 1pb "¡Olvídalo!"
    n "¡No he dicho nada!"
    mc "Debería disculparme."
    n 1bh "¿Eh?"
    mc "Te agradezco que estuvieras tratando de ser más amable."
    mc "Debería también haber sido un poco más considerado."
    mc "Pero..."
    mc "Si eso es lo que estás pensando, entonces debes saber que hay muchos interesados en chicas con cuerpos como el tuyo."
    n 1bq "Ah..."
    n "¿Tú qué...sabes de eso?"
    mc "Sólo confía en mí en este caso."
    n "..."
    n 5bx "...Asqueroso."
    mc "¡Oye!"
    mc "¿Eso fue para mí?"
    n 5bw "¿Para quién más?"
    mc "Caray..."
    mc "Sólo comencemos de una vez."
    n 2bl "¡Jajaja!"
    n "Te amargas cuando una chica te llama asqueroso."
    n 2bd "Finalmente encontré tu debilidad, [player]."
    "Natsuki sonríe maliciosamente."
    mc "Por favor, ahorratelo..."
    "Bueno, si Natsuki decide repartir más insultos así, no hay forma de que no me defienda."
    "Pero está satisfecha por ahora, finalmente comienza a sacar cosas de su bolsa para que podamos comenzar."

    scene bg kitchen
    with wipeleft_scene
    "En poco tiempo, toda la cocina es un desastre."
    "Cucharas, tazones sucios, harina, líquidos derramados y bolsas de plástico están esparcidos en cada encimera."
    "El mezclador no es lo suficientemente grande como para hacer toda la mezcla a la vez, por lo que hemos tenido que hacerla varias veces."
    "Mientras tanto, Natsuki está cuidando todos mis movimientos para asegurarse de que no estropee su preciosa repostería."
    show natsuki 2bk zorder 2 at t11
    n "[player], ¿dónde pusiste el colorante de comida?"
    n "Pronto meteré la mezcla al horno, así que necesito llenar las bandejas."
    mc "Creo que todavía está en la bolsa, al lado de la mesa."
    mc "¿Para qué lo usarás?"
    n 4bl "¡Para colorear la mezcla, por supuesto!"
    n 4bj "Haré que cada bandeja sea de un color diferente."
    n "De esta forma, incluso si los sabores no son diferentes, todos pueden elegir su favorito."
    mc "Ah, esa es una linda idea."
    mc "¿Haremos algo así con el glaseado?"
    n 4bk "¿Quieres hacerlo?"
    mc "Ah..."
    mc "¿Tú me estás preguntando a mí?"
    mc "Realmente no tengo una preferencia, entonces..."
    n 1bm "Vamos..."
    n "¡No estás poniéndole corazón a esto en absoluto!"
    n "¿Al menos puedes intentar divertirte?"
    mc "Me estoy divirtiendo..."
    "No estoy seguro de lo que Natsuki está tratando sacar de mí."
    "Mientras tanto, la veo separar la mezcla en cuencos más pequeños y poner unas gotas de colorante en cada una."
    mc "Ah, eso se ve muy bien."
    n 2bj "¿Ves?"
    n "No es como que hornear sólo se trate de seguir instrucciones."
    n "La presentación es donde puedes ser creativo y divertirte al máximo."
    n "Al final, vale la pena un millón de veces más si los ojos de todos brillan al verlos."
    mc "Como los que hiciste en mi primer día, ¿eh?"
    "Recuerdo a Natsuki presentando con orgullo sus pastelitos en forma de gato, y las expresiones de satisfacción de Sayori y Monika."
    "Me pregunto si también puedo enorgullecer a Natsuki así."
    mc "Sí..."
    mc "Entonces, puede que use el colorante de comida."
    n "Parece que estás empezando a entender."
    n "Sólo asegúrate de terminar completamente de mezclar el glaseado antes de usar el colorante."
    mc "Sí, se está haciendo."
    "El mezclador eléctrico se está usando para la mezcla principal, así que he tenido que tomar un batidor y un tazón enorme para el glaseado."
    n 4bc "¿Eh?"
    n "¡El glaseado todavía está lleno de grumos!"
    n "¿Al menos lo estás intentando?"
    mc "Bueno, sí..."
    mc "Sólo demorará un poco más."
    n 4bg "Caray, estaré aquí toda la noche si lo haces así."
    n "Así, mira."
    "Natsuki me quita el batidor y usa su otra mano para inclinar el tazón hacia atrás."
    n 4be "¡Realmente necesitas...golpearlo...muy duro!"
    "Después de unos segundos, la consistencia del glaseado mejora."
    n 4ba "¿Ves?"
    "Para enfatizar, Natsuki coloca un dedo en el glaseado y se lo mete en la boca."
    "De mala gana empiezo a hacer lo mismo."
    n 1bh "¡Oye!"
    "Natsuki de repente agarra mi muñeca."
    n 4bh "No quiero {i}tus{/i} asquerosos dedos en mi glaseado."
    mc "Tu glaseado, ¿eh?"
    mc "¿Olvidas quién hizo todo el trabajo?"
    "Empiezo a luchar, tratando de meter mi dedo en el tazón."
    n 4by "¡No me hagas golpearte!"
    mc "¡Me gustaría verte intentándolo!"
    "Me esfuerzo más, lo suficiente para que mi dedo alcance el glaseado."
    "Triunfalmente saco un poco con mi dedo justo cuando Natsuki tira con todas sus fuerzas."
    mc "¡Ah--!"
    "La fuerza de Natsuki tirando de mí me hace tropezar, haciéndola tropezar a su vez."
    n 1bx "¡Asqueroso!"
    n "¡Lo tengo en toda la cara!"
    mc "¿De quién es la culpa?"
    "Hay una gran mancha de glaseado en la mejilla de Natsuki."
    n 1bw "Nnn--"
    "Ella trata de alcanzarlo con su lengua, pero está demasiado lejos."
    n 1br "Caray..."
    n "¿Sabes qué?"
    n 4bd "¡Toma esto!"
    "Natsuki se lo limpia con el dedo y lo dirige hacia mi cara."
    mc "¡Tú lo pediste--!"
    "Soy más rápido."
    "Agarro su muñeca con mi mano antes de que llegue a mi cara."
    "Natsuki intenta usar su otra mano para defenderse, pero agarro esa también."
    $ persistent.clear[4] = True
    $ renpy.save_persistent()
    scene n_cg3_base
    show n_cg3_exp1
    show n_cg3_cake
    with dissolve_cg
    n "¡Jajajaja! ¡Detente!"
    mc "¡No hasta que te disculpes por llamarme asqueroso!"
    n "¡Bien, bien!"
    n "Lo siento por llamarte asqueroso."
    n "Sabes que no lo digo en serio."
    n "Es divertido verte reaccionar a eso."
    n "...Tú me haces eso todo el tiempo, ¿sabes?"
    n "Dices tonterías sólo para obtener una reacción de mí."
    n "Realmente no debes molestar a las chicas así."
    mc "¿Ah sí?"
    mc "En ese caso, probablemente yo tampoco debería hacer esto..."
    show n_cg3_cake at cgfade
    hide n_cg3_cake
    "Tomo el dedo de Natsuki y lo pongo en mi boca, lamiendo el glaseado."
    show n_cg3_exp1 at cgfade
    show n_cg3_exp2 at cgfade
    hide n_cg3_exp1
    n "¿Q-Q-Qué--?"
    n "¿E-En serio acabas de--"
    n "A-Ah--"
    "Natsuki está tan sorprendida que ni siquiera puede imaginarse cómo enojarse conmigo."
    "Su rostro está completamente rojo."
    hide n_cg3_exp2
    n "[player]..."
    n "Realmente no deberías hacerle ese tipo de cosas a las chicas...a menos que realmente te gusten..."
    n "Lo sabes...¿verdad?"
    mc "..."
    "¿Qué clase de pregunta me está haciendo?"
    "¿Cómo se volvió el ambiente tan loco?"
    mc "Yo..."
    "Natsuki me mira en silencio."
    "Noto sus problemas para respirar."
    "¿Por qué estoy empezando a sentirme mareado...?"
    n "¿Eh?"
    scene bg kitchen with dissolve_cg
    "De la nada, la alarma de incendios comienza a sonar."
    "Natsuki se precipita hacia el horno."
    mc "¿Hay algo ardiendo?"
    mc "Pensé que no habías puesto los pastelitos todavía."
    show natsuki 1bw zorder 2 at t11
    n "{i}*Cof*{/i}"
    n "No es de extrañarse..."
    n 1bb "¡Dejaste una bandeja sucia aquí, tonto!"
    n "¿Cómo puedes cometer un error como ese?"
    mc "¡Deberías haberlo revisado antes de encender el horno!"
    n 1bs "¡No me culpes por tus errores!"
    n "Caray..."
    "Natsuki usa una manopla para agarrar la bandeja ennegrecida del horno."
    "Ella la coloca encima de la estufa."
    "Tiempo después, la alarma de incendios se detiene."
    n 1bq "De todos modos..."
    n "Los...voy a poner en el horno ahora."
    mc "Sí..."
    "La tensión del momento anterior aún persiste en nuestras cabezas."
    "Pero el momento ya se ha perdido."
    "Observo mientras Natsuki desliza las bandejas de pastelitos en el horno."
    "Entonces, de mala gana tomo el batidor y continúo con el glaseado, como si nada hubiese pasado."

    scene bg kitchen
    show natsuki 4bz zorder 2 at t11
    with wipeleft_scene
    n "Ahh, ¡eso huele tan bien!"
    "Los pastelitos están listos para ser sacados del horno."
    "Tan pronto como Natsuki abre la puerta del horno, una ráfaga de aire cálido y olor dulce llena la habitación."
    n 4bl "¡Mira qué lindos se ven todos!"
    "Ella orgullosamente me enseña los pastelitos de diferentes colores en cada una de las bandejas."
    mc "Se verán aún mejor una vez que agreguemos el glaseado."
    n 2ba "¡No es como si necesitaras {i}decirme{/i} eso!"
    n "Traje cosas de decoración, así que espero que puedas ser creativo."
    n "Toma, mete el merengue en estas bolsas."
    "Natsuki me da algunas bolsas de plástico."
    n 2bj "Tengo estas boquillas que lo harán lucir bien y esponjoso."
    n "¡Esta incluso puede hacer flores!"
    n "Aunque, probablemente no la usemos para esta ocasión."
    mc "¿Para qué es esta?"
    "Recojo una de las boquillas que tiene una punta mucho más delgada que las otras."
    n 4bk "Esa es realmente delgada, así que puedes usarla para hacer rayas u otros patrones."
    n "Pero también puedes usarlo para escribir cosas en un pastel."
    n "Como '¡feliz cumpleaños!' o lo que sea."
    mc "Huh, ya veo..."
    mc "Eso me da una idea."
    n "¿Eh?"
    mc "Bueno, es un evento de literatura, ¿verdad?"
    mc "Podríamos darle un estilo 'literario' al escribir una palabra diferente en cada uno de los pastelitos."
    mc "Sería divertido ver a las personas elegir su pastelito según la palabra que les gusta."
    n 1bq "Uu..."
    mc "¿Hm?"
    n "Esperaba que dijeras algo realmente estúpido..."
    n 1bs "Pero eso es en realidad...una idea realmente linda, así que..."
    mc "Jajaja."
    mc "Tal vez lo estoy aprendiendo de ti."
    n 5bh "¿Q-Qué se supone que significa eso?"
    n "¡No soy linda!"
    mc "Vamos..."
    mc "No estamos en la escuela, nadie juzga."
    mc "No puedes vestirte y actuar así, y no esperar que piense que eres linda."
    n 5bs "B-Bueno..."
    "La voz de Natsuki se apaga."
    n "Lo mismo pienso de ti..."
    mc "¿Eh?"
    mc "¿Dijiste algo?"
    n 1bw "N-No, ¡nada!"
    n "¡Vamos a hacer el glaseado!"
    "Natsuki acelera el paso y sujeta una boquilla en cada una de las bolsas."
    n 1bh "¡Hay mucho que hacer, así que no deberíamos perder el tiempo!"
    n "Mira, te mostraré cómo hacerlo."
    "Sin darme la oportunidad de pensar antes, Natsuki avanza rápidamente."
    "Ella me muestra cómo aplicar el merengue, y luego nos ponemos a trabajar."

    scene bg kitchen with wipeleft_scene
    "Cuando finalmente terminamos, Natsuki los coloca lado a lado para admirar nuestro trabajo."
    show natsuki 4bl zorder 2 at t11
    n "¡Mira lo bonito que se ven juntos!"
    mc "Sí, lo son, ¿no es así?"
    n 1bm "Uju...¡ojalá pudiera comer uno ahora!"
    mc "Bueno, no hay ninguna razón por la que no puedas, ¿verdad?"
    mc "No veo ningún daño en eso."
    n 1bc "Bueno, sí, pero..."
    n "Mi papá está preparando la cena esta noche, así que realmente necesito ahorrar mi apetito."
    mc "Jajaja."
    mc "Sayori es exactamente lo opuesto en ese sentido."
    mc "Si ella estuviera aquí, probablemente ya habríamos perdido diez pastelitos."
    mc "Y aún así cenaría."
    n 4bg "¡Vamos, eso no es saludable!"
    n 4bs "Además, cuando mi papá cocina, necesito comer tanto como pueda..."
    n 4bq "...¡Bueno, como sea!"
    n 4bc "Esperaba que tuviéramos tiempo para el manga, pero necesito estar en casa para cenar..."
    mc "Ah, ¿ya te vas?"
    mc "Es una pena."
    n 1bg "¡Es tu culpa por trabajar tan despacio!"
    n "Deberías haber pensado en eso."
    n "No es como si siempre tuvieras esta oportunidad."
    mc "Caray..."
    "Como de costumbre, Natsuki me echa la culpa a mí."
    n 2bk "Puedes llevar los pastelitos mañana, ¿verdad?"
    n "Si tú y Sayori llevan cada charola, entonces probablemente puedan hacerlo en un sólo viaje."
    mc "Sí, puedo hacer eso."
    mc "Y no te preocupes, no la dejaré comer nada."
    n 2ba "Jajaja."
    n "Desearía que ella me escuchara de la manera en que te escucha."
    mc "Ah..."
    mc "Sí."
    show natsuki zorder 1 at thide
    hide natsuki
    "Recuerdo nuevamente la conversación que tuve con Sayori más temprano."
    "Me sentí tan impotente."
    "Sayori siempre me escucha, pero en ese momento sentí que no podía escucharme en absoluto."
    show natsuki 4bl zorder 2 at t11
    n "Está bien, hemos terminado"
    n "¡Bien hecho!"
    mc "Lo mismo para ti."
    mc "Supongo que...te llevaré afuera."

    scene bg house with wipeleft_scene
    "Así de simple, Natsuki ya está a punto de irse."
    "Parece que se pasó la tarde en un instante."
    "Más que eso..."
    "¿Aproveché la oportunidad para acercarme a ella, como quería?"
    show natsuki 1bh zorder 2 at t11
    n "Bueno..."
    n "Supongo que me iré..."
    n 1bq "Gracias por toda la ayuda y eso..."
    n "Te veré mañana."
    mc "Espera, Natsuki."
    n 1bh "¿Eh?"
    mc "Lo que dijiste antes...sobre no siempre tener esta oportunidad."
    mc "¡No tiene que ser así en absoluto!"
    mc "Me divertí hoy."
    mc "Me enseñaste lo divertido que puede ser hornear, justo como querías."
    mc "Pero aparte de eso..."
    mc "Puedes venir cuando quieras, ¿sí?"
    mc "Creo que si es posible, me gustaría pasar más tiempo así."
    mc "Si quieres leer manga, o salir a algún lugar--"
    n 1bm "Um--"
    n "¿Tú...lo dices en serio?"
    "Natsuki me mira tensamente, como si estuviera tratando de ocultar su expresión."
    mc "Sí."
    mc "Quiero pasar más tiempo contigo."
    n 1bq "[player]..."
    n "Pensé que sólo te importaba terminar con el trabajo..."
    n 1br "Uu..."
    n 1bn "Lo siento por tener que irme tan temprano."
    n "¡Realmente no quería!"
    n "Realmente...me quedaría aquí más tiempo si pudiera."
    n "Me siento de la misma manera que tú, así que..."
    stop music fadeout 2.0
    show natsuki 1bi at face with dissolve
    "Natsuki de repente se acerca más a mí."
    mc "Espera, Natsuki--"
    "De pie a centímetros de mí, Natsuki me mira."
    "Siento sus dedos gentilmente agarrarse a los lados de mi camisa, como si me sostuviera."
    "Sus mejillas y ojos rosados llenan mi visión, junto con sus labios ligeramente separados."
    "¿Qué esta pasando...?"
    "Mi cabeza comienza a marearse cuando siento sus suaves respiraciones contra mi."
    n 1bh "Lo he sentido..."
    n "Desde hace un tiempo..."
    n 1bo "¡¡--!!"
    show natsuki zorder 2 at t11
    "Natsuki de repente salta hacia atrás."
    n "¡¿S-Sayori?!"
    mc "¡¿Eh?!"
    show natsuki zorder 2 at t22
    show sayori 1bl zorder 3 at f21
    s "Ah..."
    s "H-Hola, [player]..."
    mc "¡Sayori--!"
    mc "Justo ahora, no estábamos--"
    s 1bq "Jejeje~"
    s "Está bien, [player]."
    s 1ba "Sólo me detuve a saludar~"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 5bq "A-Ah..."
    n "Bueno..."
    n 5bw "¡D-Deberías haber venido un poco antes!"
    n "Ya estoy yéndome, así que..."
    show natsuki zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "Aw, ¿en serio?"
    s "Que mal..."
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 2bq "Sí, bueno..."
    n "Aún así te veré en el festival mañana, así que está bien."
    n 2bb "¡No te comas los pastelitos hasta entonces!"
    n "De todos modos, ¡adiós!"
    show natsuki at lhide
    hide natsuki
    "Claramente nerviosa, Natsuki se apresura y Sayori la despide."
    return

label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "Al acercarme a mi casa, veo algo que me hace sentir un momento de pánico."
    mc "¿Yuri--?"
    show yuri 2bq zorder 2 at t11
    y "Ah..."
    y "Gracias a Dios..."
    mc "Llegaste un poco temprano..."
    mc "¡Lo siento, todavía no estaba en casa!"
    mc "¿Llevas mucho esperando?"
    y 1bf "No, acabo de llegar aquí."
    y 1bh "Pero empecé a ponerme realmente nerviosa cuando nadie respondía al timbre..."
    mc "Me podrías haber enviado un mensaje de texto."
    mc "De haberlo sabido, te habría tranquilizado y me apresuraría más en mi camino a casa."
    y 2bv "Ah...supongo que es verdad..."
    y "No pensé en eso...por alguna razón."
    "Debe ser de sentido común hacer eso, pero decido ignorarlo."
    mc "De todos modos...vamos a entrar."
    mc "Veo que trajiste muchas cosas contigo."
    y 1ba "Eso es correcto."
    y "¿Y lograste encontrar todo lo que te pedí que compraras?"
    mc "Sí, más o menos."
    mc "Al menos, espero haber tomado las cosas correctas."
    y "Estoy segura de que lo hiciste bien."
    scene bg bedroom with wipeleft
    "Llevo a Yuri a mi habitación."
    "Lo primero que hace es mirar alrededor con curiosidad, lo que me hace sentir ansioso."
    show yuri 2bm zorder 2 at t11
    y "Es tan limpio..."
    mc "Jajaja..."
    mc "Lo limpié antes de que vinieras, así que..."
    y 2ba "Eso es muy considerado de tu parte."
    mc "Ah, no..."
    mc "Me sentiría realmente avergonzado de que mi habitación fuera un desastre mientras estuvieras aquí."
    y 1ba "Hmm..."
    y "Bueno, disfruto limpiando..."
    y "Hubiera disfrutado el ayudarte a limpiar."
    mc "Ah--"
    mc "¡Eso sería aún más vergonzoso!"
    show yuri 1be
    mc "¡Espera, no mires allí...!"
    "Agarro la muñeca de Yuri, que estaba en el proceso de abrir un cajón de mi escritorio."
    y 3bn "A-Ah..."
    y "¡Lo siento...!"
    y 4bb "Por alguna razón no estaba pensando..."
    y "¡Estaba distraída!"
    mc "Está bien, está bien..."
    "Suelto la muñeca de Yuri."
    show yuri 1bl
    "Ella pone ambas manos firmemente en su regazo, como si se asegurara de vigilarlas."
    mc "Entonces, um..."
    mc "¿Deberíamos...comenzar?"
    y 2bu "Ah..."
    y "Sí..."
    y 2bf "Um, tengo algunas cosas planeadas con las que puedes ayudar..."
    y "Decoraciones y otras mejoras atmosféricas."
    mc "¿Mejoras atmosféricas...?"
    y 1ba "Ya sabes..."
    y "Iluminación de ambiente, velas de aromaterapia..."
    mc "Oh, wow."
    mc "No sabía que planeabas llevarlo tan lejos."
    y 1bc "Por supuesto."
    y "Quiero ayudar a que nuestros invitados vayan a un lugar lejano."
    y 1ba "Aunque muchos pasarán por curiosidad..."
    y 1bj "Y por...pastelitos, supongo..."
    y 1ba "Estoy decidida a brindar una experiencia que los dejará con ganas de más."
    mc "Eso es genial."
    mc "Es fácil olvidar que eres una persona muy intensa."
    y 1bt "Ah--"
    y 2bt "¿Intensa...?"
    mc "Creo que esa es la mejor manera de decirlo."
    y "¿Eso es...algo malo?"
    mc "No, en absoluto."
    mc "Es algo que me gusta de ti, en realidad."
    y 3bu "¿A-Ah sí...?"
    y "Eso me hace sentir aliviada..."
    y "Y un poco feliz..."
    mc "Sí, no hay necesidad de estar tan ansiosa."
    mc "Puedes relajarte un poco."
    y 3bl "Relajarme..."
    y 1bf "Traje algunas cosas para la relajación."
    y "Iba a usarlas durante el evento de poesía..."
    mc "¿Ah sí? ¿Como qué?"
    y "Veamos..."
    "Yuri busca en su bolso."
    "Ella saca unas velas y un objeto de madera en forma de cilindro."
    y "Hice algunas compras en el camino hasta aquí, así que las tengo en mi bolso."
    y "Planeé cubrir las ventanas en papel negro y usar las velas para iluminar la habitación."
    y 1ba "Creo que sería increíble, ¿no?"
    mc "Sí, eso sería realmente bueno."
    mc "Pero, ¿qué es eso de madera?"
    y 1bf "Oh, ¿esto?"
    y "Es un difusor para aceites esenciales."
    y "¿Qué tan familiarizado estás con la aromaterapia?"
    mc "No estoy familiarizado en absoluto..."
    y 1ba "¿Ah sí?"
    y "Es uno de mis contribuidores favoritos a una atmósfera positiva."
    y "Dependiendo de los aceites o hierbas que elija, puede cambiar el estado de ánimo del aire en sí."
    y "Incluso puedes sentir que penetra a través de tu cuerpo."
    y 3bm "Relajación, energía positiva, romance, reflexión..."
    y "Es casi como magia."
    show yuri 3ba
    "Yuri toma el cilindro y presiona un interruptor en la parte inferior."
    "En sólo un momento, un fino rayo de vapor comienza a salir a través de un pequeño orificio en la parte superior."
    mc "Wow, eso huele maravilloso."
    mc "¿De qué tipo es este?"
    y 1ba "Este es un aceite esencial de jazmín,"
    y "Huele un poco dulce y floral, ¿verdad?"
    mc "Sí, esa es una buena manera de describirlo."
    y 1bb "Elegí el Jazmín para el evento porque proporciona más que relajación."
    y "El Jazmín mejora tus emociones y te ayuda a sentirlas fluir por tu cuerpo."
    y 1bu "Te sientes más cálido y tu corazón late con más fuerza."
    y 1ba "¿No crees que será perfecto para compartir nuestros poemas?"
    mc "Suena adecuado..."
    mc "Pero parece que sabes mucho sobre esto, así que confiaré en tu opinión con cualquier cosa."
    show yuri 1bc
    "Yuri sonríe suavemente, claramente disfrutando."
    "Ella vuelve a buscar en su bolso y saca varios carretes de cinta delgada."
    show yuri 1ba
    mc "¿Para qué son?"
    y 1bf "Bueno..."
    y "¿Compraste el papel de origami que te pedí?"
    mc "Sí, lo tengo por aquí..."
    y "No usaremos el papel para plegar origami."
    y "Lo que me gustaría hacer es escribir una palabra diferente en cada papel."
    y "Necesitaremos alrededor de cien."
    mc "¿Ah, sí?"
    mc "¿Para qué se usarán?"
    y 2bf "Bueno, voy a cortar pedazos de cinta para colgarlos de la entrada del salón de clases."
    y "Entonces, podemos sujetar el papel a las cintas para crear una cortina en la entrada."
    y 2bm "¿No sería hermoso?"
    y "También llamaría la atención de los que pasan por el salón..."
    y 2ba "Puede atraer a algunos a mirar dentro."
    mc "¡Eso es realmente creativo!"
    mc "No tenía idea de que serías tan buena en esto, Yuri."
    y 4ba "¿Eso...crees?"
    y "Bueno, supongo que me pongo un poco intensa...como dirías."
    y 3bu "Jujuju."
    "Yuri se ríe con sus mejillas rojas."
    "¿Soy sólo yo, o ella está más relajada cuando somos sólo nosotros dos?"
    "O tal vez es la emoción que siente al compartir algo que le gusta."
    y 1ba "Aquí hay un plumón, [player]."
    y "Puedes escribir cualquier letra que quieras."
    y "Te ayudaré una vez que termine de cortar las cintas."
    mc "Ah, está bien."
    "Sentados juntos en el suelo, los dos nos ponemos a trabajar."
    "Escribo cuidadosamente una letra diferente en cada papel, haciendo todo lo posible con mi mala letra."
    "Yuri desenreda un largo hilo de cinta roja a su longitud deseada."
    "Entonces, vuelve a meter la mano en su bolsa y saca una navaja de bolsillo."
    mc "¿Eh...?"
    "El cuchillo es extrañamente hermoso."
    "El mango plateado tiene un intrincado patrón de ondas grabadas en él."
    "La hoja en sí está suavemente teñida de azul."
    mc "Esa no es una navaja ordinaria..."
    mc "Parece realmente elegante."
    y 4bb "A-Ah..."
    y "Bueno..."
    "Avergonzada, Yuri mira hacia otro lado."
    mc "¿Qué es?"
    y "Vas a pensar que es raro..."
    mc "Yuri, sea lo que sea, no tengo ninguna razón para juzgar."
    mc "Nunca lo he hecho, ¿sabes?"
    y "Si prometes que no te parecerá extraño..."
    mc "Sí, lo prometo."
    y 2bi "Muy bien..."
    y "El caso es que me gustan los cuchillos..."
    y "Son tan...tan bonitos..."
    y 2bv "¡No puedo evitarlo!"
    y "No sé lo que es..."
    y "La combinación de artesanía y sensación de peligro, tal vez..."
    y 4bb "Uu, ¿qué estoy diciendo...?"
    y "Por favor no pienses que soy rara por esto..."
    mc "Jajaja."
    y "Te estás riendo de mí..."
    mc "No, no me estoy riendo de ti."
    mc "Es gracioso lo nerviosa que te sentiste por compartir eso."
    mc "Es...bueno, es algo interesante en lo que estar metido, supongo."
    mc "Pero creo que te queda bien."
    y 2bt "¿Me queda...?"
    mc "Sí...es un poco intenso. Jajaja."
    mc "Además, es un cuchillo muy atractivo, no puedo negar eso."
    y 2bu "Lo es, ¿no es cierto...?"
    "Yuri relaja su expresión una vez más."
    y 1ba "¿Te gustaría sostenerlo?"
    mc "Claro, lo revisaré."
    "Yuri me pasa cuidadosamente el cuchillo, con el mango frente a mí."
    "Lo tomo y lo giro en mis manos."
    "Se siente pesado y extremadamente sólido."
    "¿Dónde se consigue un cuchillo como este...?"
    "Curioso por su nitidez, toco la punta del cuchillo con mi dedo índice."
    mc "¡Ow--!"
    y 3bn "¡¡[player]--!!"
    y "¡¿Por qué hiciste eso?!"
    mc "¡No esperaba que fuese tan filoso...!"
    mc "Apenas lo toqué."
    y "¡E-Es mi culpa!"
    y 3bo "Debería haberte advertido..."
    y "Este cuchillo es extremadamente afilado..."
    y "Puede atravesar la piel como si fuera papel."
    y 2bv "Oh no..."
    "Una pequeña gota de sangre sale por el lado de mi dedo."
    "Yuri toma mi mano y le da a la herida una mirada más cercana."
    y 2bt "Ah..."
    "Ella lo mira y se inquieta notablemente."
    mc "Si te molesta, iré a lavarlo ahora--"
    mc "¡A-Ah!"
    "Sin previo aviso, Yuri pone mi dedo en su boca y lame la herida."
    "Siento su lengua enrollada alrededor de mi dedo."
    "Sorprendido, instintivamente retiro mi mano."
    y "O-Oh..."
    y 3bo "¡P-Por favor perdóname!"
    y "¡No estaba pensando!"
    y 4bc "Yo..."
    "Yuri baja la cabeza, su cara está ardiendo."
    mc "Yuri..."
    y "Esa es la cosa más vergonzosa que he hecho..."
    y "¿Cómo podría hacer algo como eso?"
    y "Lo siento, lo siento..."
    mc "Ah..."
    "Claro, fue un poco raro, y me tomó por sorpresa..."
    "Pero supongo que ella sólo estaba tratando de ayudar, ¿verdad...?"
    mc "Yuri, creo que estás exagerando un poco..."
    y "Uuuh..."
    "Ella no levanta la cabeza."
    "¿Qué pasa si ella no se recupera de esto por el resto de la tarde?"
    mc "Muy bien, sabes qué..."
    "Esto podría ser una cosa estúpida, pero lo hago de todos modos."
    "Tomo la mano de Yuri y lamo su dedo índice a cambio."
    show yuri 3bn at h11
    y "¡¡[player]--!!"
    y "¡R-Realmente acabas de hacer eso?"
    mc "A-Ahora estamos a mano..."
    y 3bv "..."
    "Yuri simplemente me mira como si hubiera hecho algo mal."
    mc "Jajaja..."
    mc "Sabía que sería una mala idea..."
    "Si no fuera por el dulce aroma del aceite de jazmín, el aire estaría extremadamente pesado en este momento."
    y 1bu "Eres muy raro, [player]."
    "Yuri se ríe tímidamente."
    mc "¿Eh...?"
    "¿Yuri {i}me{/i} está llamando raro?"
    "No tengo respuesta a eso..."
    y 1bf "¿Dónde guardas tus vendas?"
    mc "Ah..."
    mc "No creo que necesite una, en realidad."
    mc "Fue un corte pequeño."
    mc "Mira, ya dejó de sangrar."
    y 1ba "Ya veo..."
    y "Eso es un alivio."
    "La tensión se levanta rápidamente."
    "Reanudamos nuestras actividades respectivas."
    "Veo el cuchillo de Yuri atravesar la cinta como si fuera nada más que aire."
    "Mientras tanto, sigo progresando con el papel."

    scene bg bedroom with wipeleft_scene
    "Después de terminar de colocar el papel en las cintas, los colocamos uno al lado del otro."
    "Se ve mejor de lo que esperaba y será muy eficaz como cortina de puerta."
    mc "Se ve genial."
    mc "Esto fue una buena idea, Yuri."
    show yuri 1bq zorder 2 at t11
    y "Ah, gracias..."
    y "Es algo que vi en línea, realmente."
    y 1ba "¿Estás listo para pasar a la siguiente tarea?"
    mc "Sí, hagámoslo."
    mc "¿Qué tienes en mente?"
    y "Me gustaría crear una pancarta."
    y "Es por eso que te pedí que compraras las tabletas de pintura."
    mc "Ah, es cierto."
    "Uno de los artículos que Yuri me había pedido que comprara era un juego de tabletas de pintura de acuarela."
    y 1bf "Necesitaremos alrededor de seis tazas de agua para colocar en cada una de las tabletas."
    y "¿Te importa traerlas para nosotros?"
    mc "Por supuesto que no."
    mc "Seis tazas de agua..."
    mc "Estaré de vuelta en un minuto."
    y 1ba "Muchas gracias."
    y 2bf "Ah, y sólo un poco de agua está bien."
    y "Si llenas demasiado las copas, estará demasiado diluido."

    scene bg bedroom with wipeleft_scene
    "Tomando el consejo de Yuri, decido usar pequeñas tazas de plástico para el baño en lugar de vasos de tamaño completo."
    "Las pongo en un plato para atrapar cualquier pintura que gotee, luego las llevo de vuelta a mi habitación."
    mc "¿Yuri?"
    show yuri 1bd zorder 2 at t11
    y "¿Si?"
    "Entro para ver a Yuri desenrollándose rápidamente la manga de su suéter sobre su brazo."
    mc "Ah, nada..."
    mc "Tu cara está un poco roja."
    mc "¿Hace demasiado calor aquí o algo así?"
    y 3bq "Ah--"
    y "¡No, en absoluto!"
    y "No pasa nada, así que..."
    y "Vamos a mezclar la pintura."
    "Yuri rápidamente me ignora y se encarga de desenvolver las tabletas, dejándolas caer en las tazas."
    y 1ba "Entonces..."
    y "Pensé que haríamos algo simple que se vería muy bien."
    y "Me gustaría pintar un degradado en el estandarte..."
    y "Comenzando con los colores de un amanecer, después los de el día, luego los de un atardecer y finalmente los de la noche."
    y "Una vez que se seque, escribiré una cita inspiradora en el estandarte."
    y "Podemos colgarlo en la pared del podio que está en la parte delantera del salón de clases."
    mc "Ah, genial."
    mc "¿Qué vas a escribir?"
    y 2bm "Bueno..."
    y "...Será más divertido sorprenderte."
    "Yuri me sonríe."
    mc "Si tú lo dices..."
    show yuri zorder 1 at thide
    hide yuri
    "Después de desplegar la pancarta, Yuri y yo nos arrodillamos en lados opuestos para no interferir el uno con el otro."
    "Yuri usa un pincel y agrega algunos puntos de diferentes colores en la pancarta para que sirva de guía de color cuando pintamos."
    mc "Esto me recuerda a la escuela primaria..."
    "Pintar en una pancarta con acuarelas se parece mucho a los proyectos de clase de arte que teníamos en ese momento."
    "Es relajante."
    show yuri 2bt zorder 2 at t11
    y "Ah..."
    y "¡Perdón si esto parece demasiado infantil...!"
    mc "No, no quise decir eso en absoluto."
    mc "Es divertido, ¿sabes?"
    y 1bs "...Sí."
    y "Es divertido."
    y "Me alegra que te sientas así también."
    "Yuri deja de pintar por un momento, pensando para sí misma."
    y 2bl "Para mí..."
    y "No necesito salir y hacer cosas locas para divertirme."
    y "De hecho, generalmente ni siquiera quiero."
    y 2bf "Me gusta cuando puedo pasar tiempo con otra persona..."
    y "Incluso si es algo simple, como leer, ni siquiera importa si no hablamos mucho."
    y 2ba "Sólo tener un amigo a mi lado hace que las cosas se sientan un poco más agradables."
    y "Creo que eso es todo lo que se necesita para ser feliz."
    mc "¿Ah sí...?"
    "Incluso si Yuri y yo somos diferentes, puedo entenderla."
    "Me siento así por cosas como el anime y los juegos, donde simplemente compartir la experiencia con alguien puede hacerme feliz."
    mc "Creo que siento lo mismo."
    "Yuri sonríe suavemente."
    y 1bm "Sabía que lo entenderías..."
    "Yuri se inclina sobre la pancarta para agarrar un pincel sin usar."
    "Pero me muevo al mismo tiempo, haciendo que mi cabeza se tope con la de ella."
    y 3bn "¡Kya--!"
    mc "¡L-Lo siento!"
    "Yuri retrocede, y rápidamente alzo las manos, sorprendido."
    mc "¿Estás herida?"
    y 2bv "N-No, no estoy herida."
    y "Simplemente me sobresalte...eso es todo."
    y "Lo siento, debería haberte pedido que me lo pasaras..."
    mc "No es tu culpa."
    mc "Ah, tu cara..."
    "Hay gotitas de pintura en la cara y en el cuello de Yuri."
    y 2bt "¿Hay algo en mi cara?"
    mc "Sí, accidentalmente te pinté..."
    mc "¡Lo siento, es totalmente mi culpa!"
    mc "Traeré una toalla de inmediato."
    show yuri zorder 1 at thide
    hide yuri
    "Salgo corriendo a buscar una toalla pequeña, luego la humedezco con agua caliente."
    "Regreso a mi habitación y me arrodillo frente a ella."
    $ persistent.clear[5] = True
    $ renpy.save_persistent()
    scene y_cg3_base with dissolve_cg
    mc "Toma..."
    "Palpo la cara y el cuello de Yuri con la toalla."
    show y_cg3_exp1 at cgfade
    y "Ah--"
    mc "¿Pasa algo?"
    y "Está caliente...simplemente no lo esperaba."
    mc "Lo siento..."
    mc "No quería usar agua fría."
    "Al terminar, empiezo a retraer mi mano."
    "Pero Yuri de repente sostiene mi muñeca."
    hide y_cg3_exp1
    y "Espera--"
    mc "¿Eh?"
    show y_cg3_exp1 at cgfade
    y "Sólo...un rato más."
    y "Se siente muy bien..."
    mc "Ah..."
    "Mantengo mi mano quieta contra el rostro de Yuri."
    hide y_cg3_exp1
    "Ella me mira a los ojos."
    "Es una expresión intensa que reconozco cuando lee sus libros..."
    "Casi como si estuviera perdida en un aturdimiento, envuelta en sus propios pensamientos."
    "Respira suavemente, la mitad a través de sus labios ligeramente separados."
    "¿Qué está pasando...?"
    "¿Es el aroma del aceite de jazmín lo que me produce esta sensación de vértigo?"
    "Los suaves dedos de Yuri, envueltos alrededor de mi muñeca, provocan una sensación de hormigueo en mi brazo."
    "Y de repente, su rostro parece estar mucho más cerca del mío que hace un momento..."
    y "Ah..."
    "Yuri lentamente se aleja."
    y "Lo siento..."
    y "Me he sentido un poco mareada hoy."
    y "No quise distraerme..."
    mc "E-Está bien..."
    scene bedroom with dissolve_cg
    "El momento ha terminado tan pronto como comenzó."
    "Yuri vuelve a tomar su pincel."
    "Pero sus movimientos parecen más torpes, como si no pudiera enfocarse."
    "Permanezco en silencio, forzado a ignorar lo que acaba de ocurrir."
    "Tomo mi pincel con vacilación y continúo siguiendo el ejemplo de Yuri."

    scene bedroom with wipeleft_scene
    mc "Eso debería ser todo..."
    "Termino de llenar el cielo nocturno con puntos blancos que parecen estrellas."
    "Al mirar la pancarta como un todo, es muy bonita y de aspecto natural."
    show yuri 1ba zorder 2 at t11
    y "Creo que salió mejor de lo que esperaba."
    y "Estoy muy feliz con los resultados."
    mc "Sí, yo también."
    mc "¿Vas a agregar las letras ahora?"
    y 1bf "Ah, todavía no..."
    y "Necesita secarse primero."
    mc "Eso es cierto, pero, ¿no tomará un tiempo?"
    y 2bh "Bueno..."
    y "Quizás sería mejor dejarlo aquí, y luego lo lleves por la mañana."
    y 2bf "Puedo escribir las letras en el salón antes de que comience nuestro evento."
    y "¿Está bien?"
    mc "Eso está totalmente bien."
    y 1ba "Maravilloso."
    y "En ese caso..."
    y "No creo que haya nada más que hacer aquí."
    mc "Uff."
    y 1bc "Jajaja."
    y "Dices eso como si estuvieras contento de que todo haya terminado."
    y 1ba "¿Estaba equivocada al suponer que al menos te estabas divirtiendo un poco?"
    mc "Ah, no, no es eso."
    mc "Sólo estoy feliz de que logramos hacer todo."
    y 2ba "Ya veo."
    y "Yo también lo estoy."
    y "Me preocupaba un poco el tiempo..."
    y "Necesito comenzar a preparar la cena pronto."
    mc "Ah..."
    mc "¿Entonces no te queda tiempo?"
    "Esperaba en secreto que tuviéramos tiempo extra después de terminar el trabajo..."
    y 2bl "Bueno..."
    y "..."
    "Yuri piensa para sí misma."
    y 3bv "Yo...creo que sería demasiado irresponsable por mi parte esperar mucho más tiempo..."
    y "¡Lo siento!"
    y "También esperaba que hubiera más tiempo..."
    mc "Probablemente es mi culpa."
    mc "Perdón por ser un trabajador lento."
    y 1bt "No, no es tu culpa en absoluto."
    y "Y...lo importante es que tenemos todo hecho, ¿no?"
    mc "Sí..."
    y 1bu "Entonces..."
    y "No debería ser decepcionante...ni nada parecido."
    "Juntando todas sus cosas, Yuri parece estar un poco abatida."
    "Entiendo por qué."
    "Parecía que rara vez tiene la oportunidad de pasar tiempo con amigos en un ambiente relajado."
    "Pero eso no significa que esta sea la última vez que puede pasar..."

    scene bg house with wipeleft_scene
    "Una vez que Yuri empaca, la llevo a la puerta."
    show yuri 1ba zorder 2 at t11
    y "Muchas gracias por recibirme hoy."
    mc "No hay problema, me alegro de poder ayudar."
    mc "Sólo avísame si necesitas que lleve algo más para mañana."
    y "Lo haré."
    y 1bu "Bueno, entonces..."
    "Yuri se inquieta."
    y 2bu "Supongo que...te veré mañana."
    mc "Espera--"
    show yuri 2bt
    "Como que digo eso sin pensar."
    mc "Sobre lo que pasó hoy..."
    mc "Está bien que no tengamos tanto tiempo como quisiéramos."
    mc "Porque podemos hacer esto de nuevo."
    mc "Siempre que quieras, puedes venir, o podemos ir a algún lado..."
    mc "Ah, olvidé que no te gusta salir mucho--"
    show yuri 2bs
    "Mientras me tropiezo con mis palabras, Yuri simplemente sonríe tímidamente."
    mc "De todos modos..."
    mc "Sabes lo que estoy tratando de decir, entonces..."
    y 1bs "Eres muy considerado, [player]."
    "Yuri da un paso para acercase a mí, luego aprieta mi mano brevemente."
    show yuri 2bs at face(y=600) with dissolve
    stop music fadeout 2.0
    y "Me gusta eso de ti..."
    mc "Bueno..."
    "¿Cómo se supone que debo responder a eso?"
    "Pero ni siquiera tengo la oportunidad de hacerlo, ya que Yuri de repente retrocede."
    show yuri 3bn zorder 2 at t11
    y "¿S-Sayori--?"
    mc "¡¿Eh?!"
    show sayori 1bl zorder 3 at f21
    show yuri zorder 2 at t22
    s "Ah..."
    s "H-Hola, [player]..."
    mc "¡Sayori--!"
    mc "Justo ahora, no estábamos--"
    s 1bq "Jejeje~"
    s "Está bien, [player]."
    s 1ba "Sólo me detuve para saludar~"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 3bq "U-Um..."
    y "Pues, es bueno verte..."
    y 3bv "Lo siento, ¡pero ya me voy!"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "Aw, ¿en serio?"
    s "Que mal..."
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 2bt "Lo siento..."
    y "Pero todos estaremos juntos en el festival de mañana, así que..."
    y "Así que está bien, ¿verdad?"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 4bq "¡Claro!"
    "Sayori sonríe."
    show sayori 4ba
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 4bc "S-Sí, entonces..."
    y "¡Te veré mañana!"
    show yuri at lhide
    hide yuri
    "Claramente avergonzada, Yuri se apresura."
    "Sayori la despide."
    return



label ch4_end:
    play music t10 fadeout 2.0
    show sayori 1ba zorder 2 at t11
    mc "Sayori--"
    mc "¡Pensé que no querías venir hoy!"
    s 2bl "Jajaja, bueno..."
    s "Intenté quedarme en mi habitación..."
    s "Pero mi imaginación estaba siendo realmente mala conmigo..."
    s 1by "Así que tuve que venir aquí y verlo por mí misma."
    mc "¿Ver qué?"
    mc "¿De qué estás hablando?"
    s "Ya sabes..."
    s "Ver cuanta diversión tenías con [ch4_name]."
    s "Y qué tan cerca estuviste con ella."
    s 1bt "Me hace...sealmente feliz..."
    s "Saber que has hecho tan buenas amigas."
    s "Eso es todo lo que me importa."
    "Las lágrimas comienzan a caer en la cara de Sayori."
    s 4bv "¡Eso es todo lo que me importa--!"
    s "¿Por qué me siento así, [player]?"
    s "Se supone que debo alegrarme por ti."
    s 4bw "¿Por qué se siente como si mi corazón se está partiendo por la mitad?"
    s "Duele mucho..."
    s "Todo duele mucho..."
    s "¡Esto sería mucho mejor si pudiera desaparecer!"
    mc "¡Sayori, no digas eso!"
    s 1bw "¡Es cierto, [player]!"
    s "¡Si no estuviera aquí, entonces no tendrías que gastar tu simpatía en mí!"
    s "¡No tendrías que soportar que yo sea egoísta!"
    s 1bv "Monika tenía razón..."
    s "Debería simplemente..."
    mc "¿Monika...?"
    mc "¿Monika tenía razón sobre qué?"
    s "..."
    mc "Sayori..."
    mc "Lo que dije antes es verdad."
    mc "No voy a dejar que esto continúe."
    mc "Cuidar de ti de esta manera no es la carga que tu mente está imaginando."
    mc "Es algo que me hace feliz."
    mc "Es algo que no cambiaría por nada más."
    mc "Entonces, incluso si toma toda una vida..."
    mc "Voy a estar a tu lado hasta que no sientas más dolor."
    s 1bk "P-Pero..."
    "Sayori mira hacia otro lado."
    "Pongo una mano en su hombro para tranquilizarla."
    s "Tengo miedo, [player]..."
    s "Tengo mucho miedo..."
    mc "¿De qué tienes miedo, Sayori?"
    s "Tengo miedo de que..."
    s "Me gustes más de lo que te gusto.."
    mc "¿Sayori...?"
    s 1bu "Es cierto, ¿verdad?"
    s "Estaba débil y comenzaste a gustarme demasiado..."
    s "Me hice esto a mí misma."
    s "[player]..."
    s 4bw "¡Me gustas tanto que quiero morir!"
    s "¡Así es como me siento!"
    s 2bv "Y...y..."
    mc "Es suficiente, Sayori..."
    mc "No quiero que te lastimes más."
    "Deslizo mi mano por el brazo de Sayori y aprieto su mano con la mía."
    mc "¿Recuerdas cómo dije que siempre sé lo que es mejor para ti?"
    mc "¿Todavía me crees?"
    "Sin decir ninguna palabra, Sayori asiente."
    mc "Incluso si no entiendes todos tus propios sentimientos..."
    mc "Sé lo que más necesitas ahora."
    mc "Y eso es lo que voy a darte."
    show black zorder 4 with dissolve_cg

    menu:
        mc "Sayori..."
        "Te amo.":

            $ sayori_confess = True
            hide black with dissolve_cg
            call ch4_end_yes from _call_ch4_end_yes
        "Siempre serás mi mejor amiga.":
            $ sayori_confess = False
            hide black with dissolve_cg
            call ch4_end_no from _call_ch4_end_no

    return

label ch4_end_yes:
    mc "Te amo."
    s 1bv "¿Eh--?"
    mc "Esos son mis verdaderos sentimientos."
    mc "Entonces...no hay forma de que te pueda gustar más de lo que me gustas."
    mc "Debería haberme dado cuenta antes."
    mc "Pero pasar tiempo con todas en el club..."
    mc "Hacer nuevos amigos..."
    mc "Y divertirme contigo todos los días..."
    mc "Me ayudó a darme cuenta de que eres la persona más importante para mí."
    mc "Es por eso que aceptaré cualquiera de tus cargas."
    mc "Mientras continuemos así todos los días..."
    mc "Contigo a mi lado..."
    mc "Entonces sé que ambos seremos felices."
    s "[player]..."
    $ persistent.clear[8] = True
    $ renpy.save_persistent()
    scene s_cg3 with dissolve_cg
    "De repente, Sayori me abraza fuertemente."
    s "[player]..."
    s "¿Esto...está realmente bien?"
    mc "Sí."
    "Sostengo a Sayori en mis brazos y la acerco."
    mc "Nunca más tendrás que soltarme."
    s "Te amo, [player]..."
    s "Quiero estar contigo para siempre."
    mc "Yo también."
    s "..."
    "Siento que el agarre de Sayori a mi alrededor se debilita un poco."
    s "¿Qué es esto...?"
    mc "Sayori...?"
    s "Se supone que debo ser feliz en este momento..."
    s "Siempre pensé que este sería el momento más feliz para mí."
    s "¿Pero por qué...?"
    s "Incluso ahora..."
    s "¿Por qué las nubes de lluvia no desaparecen?"
    s "No van a desaparecer para nada, [player]..."
    mc "Está bien, Sayori..."
    mc "Puede tomar algo de tiempo para que las cosas mejoren nuevamente."
    mc "Pero no importa cuánto tiempo tome, estaré allí en cada paso del camino."
    mc "Eso es todo lo que importa en este momento."
    s "V-Vale..."
    s "Yo...confío en ti..."
    scene bg house
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Sayori y yo nos soltamos lentamente el uno al otro."
    mc "Entonces..."
    mc "Supongo que eso hace al festival de mañana...nuestra primera cita, ¿eh?"
    s 1by "Jejeje..."
    s "¿Qué estás diciendo?"
    s "No quiero pensar en esas cosas, ¿sabes?"
    s "Quiero que todo sea igual a como siempre ha sido."
    s "Incluso si realmente somos...una pareja."
    s 1bk "No sé si podría soportar algo más por ahora..."
    s "Es realmente nuevo y atemorizante para mí."
    mc "Lo entiendo."
    mc "Iremos al ritmo que más te convenga."
    s 1bd "Oye, [player]..."
    "Sayori me mira una vez más, sonriendo tristemente."
    s 4bd "Incluso si me siento muy, muy triste..."
    s "Esto es lo mejor para mí...¿verdad?"
    mc "¿Eh...?"
    "Realmente no entiendo lo que Sayori quiere decir con eso."
    mc "¿Estás diciendo que esto te está haciendo sentir triste, Sayori?"
    s 4bk "No lo sé..."
    s "No entiendo lo que estoy sintiendo."
    s "Se sintió como un montón de espinas cuando me dijiste que me amas..."
    s 4bd "Pero es por eso que quiero confiar en ti."
    s "Sabes lo que es mejor para mí..."
    mc "...Sí."
    mc "Sí."
    mc "Esa es mi promesa."
    show sayori zorder 1 at thide
    hide sayori
    "Digo eso, pero en realidad, nunca me he sentido más incierto sobre Sayori que ahora."
    "Sé que la amo y ella me ama."
    "Pero estoy teniendo tantos problemas para entender los sentimientos de Sayori tanto como ella."
    "Aunque puedo consolarla..."
    "Me sigo preguntando si debería estar haciendo algo más, o algo diferente."
    "Sé que estos pensamientos seguirán atormentándome hasta que las cosas vuelvan a ser como antes."
    "¿Es eso lo que Sayori quiso decir con no querer que nada cambie?"
    "No lo sé.."
    "Pero sé que le daré todo lo que tengo."
    "Sayori es la persona más importante para mí."
    "Y haré lo que sea necesario para tener un futuro feliz con ella."
    return


label ch4_end_no:
    mc "Siempre serás mi mejor amiga."
    mc "Lo que más necesitas es que las cosas sean como siempre lo han sido."
    mc "Monika me dijo la verdad..."
    mc "Ella me dijo cuánto más feliz parecías después de unirme al club."
    mc "Sé que estás luchando con sentimientos realmente complicados en este momento."
    mc "Pero..."
    mc "Por favor, creeme que sé lo que es mejor...y lo que te hará feliz al final."
    mc "Prometo que ayudaré a que las cosas vuelvan a ser como antes"
    s 1bt "Yo..."
    s "Yo...lo sé..."
    "Sayori fuerza una sonrisa a través de una expresión de increíble dolor."
    s "Jajaja..."
    s "¿Es esto lo que se siente...ser apuñalado en el pecho?"
    s "Debo escribir un poema sobre esto..."
    mc "Sayori--"
    s "Está bien."
    s "Este es sólo mi castigo...¿recuerdas?"
    s "Por ser tan egoísta..."
    s "Así que por favor..."
    s "Por favor, no te preocupes por estos estúpidos sentimientos."
    s "Sé que tienes razón."
    s "Sabía todo este tiempo que no hay felicidad de esa manera."
    s "Es por eso que vine aquí..."
    s "Sólo para poder obtener la respuesta que necesitaba escuchar."
    s "Y la otra cosa..."
    s "También tienes razón de que sólo quiero que todo vuelva a ser como era."
    s "Me doy cuenta de eso ahora."
    s "Realmente me conoces mejor que nadie, [player]."
    s 4bv "Te confiaré cualquier cosa..."
    s "Lo que sea..."
    s "Entonces..."
    show sayori zorder 1 at thide
    hide sayori
    "La sonrisa de Sayori finalmente se rompe."
    "De repente, ella se da vuelta y cae de rodillas."
    s "{i}¡¡¡¡AAAAAaaaaAAAAAAAAHH!!!!{/i}"
    "Agarrando su cabeza con ambas manos, grita tan fuerte como puede."
    "Estoy tan sorprendido que no sé cómo reaccionar."
    show sayori 4bt zorder 2 at t11
    s "..."
    show sayori at lhide
    hide sayori
    "Sayori mira por encima del hombro y me lanza una sonrisa débil más antes de darse la vuelta y salir corriendo."
    mc "¡Sayori!"
    "..."
    "Me quedo impotente en el frente de mi casa."
    "¿Por qué me siento tan mal por esto?"
    "No hay nada más que podría haber hecho."
    "Lo único que puedo hacer es apoyar a Sayori con sus sentimientos y ayudarla de la manera correcta."
    "Pero estoy teniendo problemas para entender los sentimientos de Sayori, tanto como ella."
    "Aunque pueda consolarla..."
    "Me sigo preguntando si debería estar haciendo algo más, o algo diferente."
    "Sé que estos pensamientos seguirán atormentándome hasta que las cosas vuelvan a ser como antes."
    "Voy a darle todo lo que tengo."
    "Sayori siempre será mi mejor amiga."
    "Y haré lo que sea necesario para poner una sonrisa en su rostro todos los días."

    return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
